import 'dotenv/config'
import pkg from '@prisma/client'
const { PrismaClient } = pkg
import { PrismaMariaDb } from '@prisma/adapter-mariadb'

const adapter = new PrismaMariaDb(process.env.DATABASE_URL as string)
const prisma = new PrismaClient({ adapter })

const properties = [
  {
    title: 'Luxury BGC Skyline Condo',
    description: 'Experience premium living in the heart of Bonifacio Global City. Fully furnished with high-end appliances, floor-to-ceiling windows, and access to world-class amenities.',
    price: 85000,
    address: '5th Avenue, Bonifacio Global City',
    city: 'Taguig City',
    state: 'Metro Manila',
    zipCode: '1634',
    beds: 2,
    baths: 2,
    sqft: 1200,
    type: 'CONDO',
    amenities: ['Swimming Pool', 'Gym', '24/7 Security', 'Balcony', 'Parking', 'Fully Furnished'],
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Modern Single Attached House in Bacoor',
    description: 'A spacious and modern family home located in a highly secured subdivision. Just 20 minutes away from Mall of Asia via CAVITEX.',
    price: 35000,
    address: 'Camella Homes, Salinas I',
    city: 'Bacoor',
    state: 'Cavite',
    zipCode: '4102',
    beds: 4,
    baths: 3,
    sqft: 2500,
    type: 'HOUSE',
    amenities: ['Garage', 'Garden', 'Gated Community', 'Clubhouse', 'Playground'],
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Cozy Studio in Makati CBD',
    description: 'Perfect for young professionals. Walking distance to Ayala Avenue, Greenbelt, and Glorietta malls. Great city views from the 35th floor.',
    price: 25000,
    address: 'Salcedo Village',
    city: 'Makati City',
    state: 'Metro Manila',
    zipCode: '1227',
    beds: 1,
    baths: 1,
    sqft: 450,
    type: 'APARTMENT',
    amenities: ['Gym', 'Concierge', 'Air Conditioning', 'Pet Friendly'],
    images: ['https://images.unsplash.com/photo-1502672260266-1c1de2d9d000?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Cool Breeze Tagaytay Retreat House',
    description: 'Escape the city heat in this beautiful rest house in Tagaytay. Features a massive lawn, outdoor BBQ area, and cool pine-scented breeze all year round.',
    price: 45000,
    address: 'Brgy. San Jose',
    city: 'Tagaytay City',
    state: 'Cavite',
    zipCode: '4120',
    beds: 3,
    baths: 2,
    sqft: 1800,
    type: 'HOUSE',
    amenities: ['Garden', 'Patio', 'Fireplace', 'Parking', 'Scenic View'],
    images: ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Executive Townhouse in Quezon City',
    description: '3-story modern townhouse near UP Diliman and Ateneo. Ideal for growing families with excellent access to top-tier schools and hospitals.',
    price: 40000,
    address: 'Teachers Village',
    city: 'Quezon City',
    state: 'Metro Manila',
    zipCode: '1101',
    beds: 3,
    baths: 3,
    sqft: 2100,
    type: 'TOWNHOUSE',
    amenities: ['2-Car Garage', 'Maids Room', 'Balcony', 'Gated Security'],
    images: ['https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Ortigas Center High-Rise Condo',
    description: 'Premium condominium right beside SM Megamall and EDSA Shangri-La. Fully fitted kitchen, smart home capabilities, and direct mall access.',
    price: 60000,
    address: 'Ortigas Center',
    city: 'Pasig City',
    state: 'Metro Manila',
    zipCode: '1605',
    beds: 2,
    baths: 2,
    sqft: 950,
    type: 'CONDO',
    amenities: ['Smart Home', 'Pool', 'Fitness Center', 'Direct Mall Access'],
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Quiet Suburban Home in Dasmariñas',
    description: 'Located in a peaceful neighborhood near DLSU Dasmariñas. Newly painted with a large backyard perfect for outdoor gatherings.',
    price: 22000,
    address: 'Salitran II',
    city: 'Dasmariñas',
    state: 'Cavite',
    zipCode: '4114',
    beds: 3,
    baths: 2,
    sqft: 1500,
    type: 'HOUSE',
    amenities: ['Backyard', 'Garage', 'Pet Friendly'],
    images: ['https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Alabang Elegant Family Mansion',
    description: 'A luxurious property in Ayala Alabang Village. Features a private pool, massive chef\'s kitchen, and highly secure exclusivity.',
    price: 180000,
    address: 'Ayala Alabang Village',
    city: 'Muntinlupa',
    state: 'Metro Manila',
    zipCode: '1780',
    beds: 5,
    baths: 4,
    sqft: 5000,
    type: 'HOUSE',
    amenities: ['Private Pool', 'Chef Kitchen', 'Home Theater', 'High Security'],
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Manila Bayview Apartment',
    description: 'Enjoy the world-famous Manila Bay sunset right from your own balcony. Very accessible to Malate and Ermita districts.',
    price: 32000,
    address: 'Roxas Boulevard',
    city: 'Manila',
    state: 'Metro Manila',
    zipCode: '1000',
    beds: 2,
    baths: 1,
    sqft: 800,
    type: 'APARTMENT',
    amenities: ['Sea View', 'Balcony', 'Gym', '24/7 Security'],
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Modern Townhouse in General Trias',
    description: 'Brand new construction in Lancaster New City. Very accessible to schools, supermarkets, and the upcoming CALAX.',
    price: 18000,
    address: 'Lancaster New City',
    city: 'General Trias',
    state: 'Cavite',
    zipCode: '4107',
    beds: 3,
    baths: 2,
    sqft: 1100,
    type: 'TOWNHOUSE',
    amenities: ['Clubhouse', 'Basketball Court', 'Parking'],
    images: ['https://images.unsplash.com/photo-1558036117-15d82a90b9b1?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Silang Countryside Villa',
    description: 'A sprawling peaceful estate surrounded by pineapple plantations. Just 15 minutes away from Tagaytay roundabout.',
    price: 55000,
    address: 'Brgy. Tartaria',
    city: 'Silang',
    state: 'Cavite',
    zipCode: '4118',
    beds: 4,
    baths: 3,
    sqft: 3200,
    type: 'HOUSE',
    amenities: ['Large Garden', 'Fruit Trees', 'Outdoor Gazebo'],
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Parañaque Airport-Adjacent Condo',
    description: 'Highly convenient for frequent flyers. Literal walking distance to NAIA Terminal 3 and Newport World Resorts.',
    price: 38000,
    address: 'Resorts World Boulevard',
    city: 'Parañaque City',
    state: 'Metro Manila',
    zipCode: '1709',
    beds: 1,
    baths: 1,
    sqft: 550,
    type: 'CONDO',
    amenities: ['Pool', 'Gym', 'Casino Access', 'Shuttle Service'],
    images: ['https://images.unsplash.com/photo-1502672260266-1c1de2d9d000?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Las Piñas Cozy Starter Home',
    description: 'Perfect for newlyweds or small families. Within BF Resort Village, known for its community safety and great food spots.',
    price: 26000,
    address: 'BF Resort Village',
    city: 'Las Piñas City',
    state: 'Metro Manila',
    zipCode: '1740',
    beds: 2,
    baths: 1,
    sqft: 1300,
    type: 'HOUSE',
    amenities: ['Garage', 'Gated Subdivision', 'Nearby Restaurants'],
    images: ['https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Imus Commercial-Residential Apartment',
    description: 'Located along Emilio Aguinaldo Highway. Convenient first-floor living with direct access to local transport and markets.',
    price: 15000,
    address: 'Tanzang Luma',
    city: 'Imus',
    state: 'Cavite',
    zipCode: '4103',
    beds: 1,
    baths: 1,
    sqft: 600,
    type: 'APARTMENT',
    amenities: ['Highway Access', 'CCTV Security'],
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800&h=600'],
  },
  {
    title: 'Trece Martires Corner Lot House',
    description: 'Spacious corner lot in the heart of the provincial capital. Walking distance to SM City Trece Martires and the provincial capitol.',
    price: 24000,
    address: 'San Agustin',
    city: 'Trece Martires',
    state: 'Cavite',
    zipCode: '4109',
    beds: 3,
    baths: 2,
    sqft: 1600,
    type: 'HOUSE',
    amenities: ['Corner Lot', 'Garage', 'Garden'],
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800&h=600'],
  }
]

async function main() {
  console.log('Seeding Philippine properties...')
  for (const p of properties) {
    const propertyType = p.type as any 
    await prisma.property.create({
      data: {
        title: p.title,
        description: p.description,
        price: p.price,
        address: p.address,
        city: p.city,
        state: p.state,
        zipCode: p.zipCode,
        beds: p.beds,
        baths: p.baths,
        sqft: p.sqft,
        type: propertyType,
        amenities: p.amenities,
        images: p.images,
      }
    })
  }
  console.log('Finished seeding 15 properties!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
